Repository cmorten/opine, pull requests merged in 2020-06, with the labels that each got.

#11 [NO-ISSUE] Add Opine Icon
  .github/icon.jpg
  .github/icon.png
  .github/icon.svg
  README.md
  docs/classes/_response_.response.html
  docs/index.html
  docs/interfaces/_types_.application.html
  docs/interfaces/_types_.byterange.html
  docs/interfaces/_types_.handler.html
  docs/interfaces/_types_.iroute.html
  docs/interfaces/_types_.irouter.html
  docs/interfaces/_types_.irouterhandler.html
  docs/interfaces/_types_.iroutermatcher.html
  docs/interfaces/_types_.mediatype.html
  docs/interfaces/_types_.nextfunction.html
  docs/interfaces/_types_.opine.html
  docs/interfaces/_types_.request.html
  docs/interfaces/_types_.requesthandler.html
  docs/interfaces/_types_.response.html
  docs/interfaces/_types_.router.html
  docs/interfaces/_types_.routerconstructor.html
  docs/interfaces/_types_.routeroptions.html
  docs/modules/_application_.html
  docs/modules/_methods_.html
  docs/modules/_middleware_bodyparser_getcharset_.html
  docs/modules/_middleware_bodyparser_json_.html
  docs/modules/_middleware_bodyparser_raw_.html
  docs/modules/_middleware_bodyparser_read_.html
  docs/modules/_middleware_bodyparser_text_.html
  docs/modules/_middleware_bodyparser_typechecker_.html
  docs/modules/_middleware_bodyparser_urlencoded_.html
  docs/modules/_middleware_init_.html
  docs/modules/_middleware_query_.html
  docs/modules/_middleware_servestatic_.html
  docs/modules/_opine_.html
  docs/modules/_request_.html
  docs/modules/_router_index_.html
  docs/modules/_router_layer_.html
  docs/modules/_router_route_.html
  docs/modules/_types_.html
  docs/modules/_utils_compileetag_.html
  docs/modules/_utils_contentdisposition_.html
  docs/modules/_utils_definegetter_.html
  docs/modules/_utils_etag_.html
  docs/modules/_utils_finalhandler_.html
  docs/modules/_utils_fresh_.html
  docs/modules/_utils_merge_.html
  docs/modules/_utils_mergedescriptors_.html
  docs/modules/_utils_normalizetype_.html
  docs/modules/_utils_parseurl_.html
  docs/modules/_utils_pathtoregex_.html
  docs/modules/_utils_stringify_.html
Labels: documentation

#12 [#10] egg.json for nest.land integration
  egg.json
Labels: chore

#13 [#10] Nest land package publish
  .github/CHANGELOG.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish-egg.yml
  Makefile
  egg.json
  version.ts
Labels: chore

#15 [#14] Add repository to egg.json
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-egg.yml
  egg.json
  version.ts
Labels: feature

#30 [#29] Automate typedoc publish
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish-docs.yml
  Makefile
  repro-example/deps.ts
Labels: automation, chore

#35 [#20] Add instructions for nest.land package registry
  README.md
Labels: documentation

#33 [#34] Capture errors from async routes
  src/router/layer.ts
  test/units/Router.test.ts
Labels: feature

#36 [#22] Add res.redirect API
  .github/API/response.md
  examples/README.md
  examples/redirect/README.md
  examples/redirect/index.ts
  src/response.ts
  src/types.ts
  test/deps.ts
  test/units/res.redirect.test.ts
  test/utils.ts
Labels: feature
