Repository cmorten/opine, pull requests merged in 2020-12, with the labels that each got.

#90 [NO-ISSUE] Deno 1.5.4 and std 0.79.0
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  Makefile
  README.md
  deps.ts
  docs/assets/js/main.js
  docs/index.html
  egg.json
  lock.json
  src/middleware/query.ts
  src/utils/compileQueryParser.ts
  test/deps.ts
  version.ts
Labels: chore

#89 Missing closed parentheses on docs
  .github/API/request.md
Labels: documentation

#88 [NO-ISSUE] Update main README example to use get method with specific route
  README.md
Labels: documentation

#91 [NO-ISSUE] Support Deno 1.6.0
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  docs/index.html
  egg.json
  lock.json
  test/deps.ts
  test/units/res.sendFile.test.ts
  test/units/serveStatic.test.ts
  test/utils.ts
  version.ts
Labels: chore, dependencies

#93 Fix heading in request API documentation
  .github/API/request.md
Labels: documentation

#94 [#92] Support Deno 1.6.1 and fix eggs CLI publish
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  docs/assets/js/main.js
  docs/index.html
  egg.json
  lock.json
  test/deps.ts
  test/units/res.redirect.test.ts
  test/units/serveStatic.test.ts
  version.ts
Labels: dependencies

#85 [#75] File options support
  .github/API/middlewares.md
  .github/API/response.md
  deps.ts
  docs/assets/js/main.js
  lock.json
  src/methods.ts
  src/middleware/serveStatic.ts
  src/response.ts
  src/types.ts
  src/utils/etag.ts
  src/utils/fresh.ts
  src/utils/send.ts
  src/view.ts
  test/fixtures/.name
  test/units/bodyParser.json.test.ts
  test/units/bodyParser.raw.test.ts
  test/units/bodyParser.text.test.ts
  test/units/bodyParser.urlencoded.test.ts
  test/units/res.download.test.ts
  test/units/res.send.test.ts
  test/units/res.sendFile.test.ts
  test/units/serveStatic.test.ts
  test/utils.ts
Labels: feature

#95 [#26] Implement request body proxy
  .github/API/middlewares.md
  .github/API/request.md
  .github/CHANGELOG.md
  examples/json/index.ts
  examples/mvc/controllers/pet/index.ts
  examples/mvc/controllers/user-pet/index.ts
  examples/mvc/controllers/user/index.ts
  examples/raw/index.ts
  examples/text/index.ts
  examples/urlencoded/index.ts
  src/application.ts
  src/middleware/bodyParser/urlencoded.ts
  src/types.ts
  src/utils/requestProxy.ts
Labels: feature

#99 [#97] Support --no-check flag
  deps.ts
  lock.json
Labels: dependencies

#100 [NO-ISSUE] Opine 1.0.1
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/test.yml
  Makefile
  README.md
  deps.ts
  docs/index.html
  egg.json
  lock.json
  test/deps.ts
  version.ts
Labels: dependencies
