Repository cmorten/opine, pull requests merged in 2020-07, with the labels that each got.

#37 [NO-ISSUE] Add swagger doc example
  examples/swagger/README.md
  examples/swagger/controllers/v1.ts
  examples/swagger/index.ts
Labels: documentation

#38 [#23] Array support for `res.append`
  .github/API/response.md
  src/response.ts
  src/types.ts
  test/units/res.append.test.ts
Labels: feature

#43 [#42] Incorrect URL argument type
  .github/workflows/test.yml
  deps.ts
  docs/assets/js/main.js
  lock.json
  src/middleware/serveStatic.ts
  version.ts
Labels: bug
