Repository cmorten/opine, pull requests merged in 2020-08, with the labels that each got.

#46 Feat/issue 21 add app param api
  docs/assets/js/search.json
  docs/classes/_response_.response.html
  docs/classes/_view_.view.html
  docs/interfaces/_types_.application.html
  docs/interfaces/_types_.byterange.html
  docs/interfaces/_types_.handler.html
  docs/interfaces/_types_.iroute.html
  docs/interfaces/_types_.irouter.html
  docs/interfaces/_types_.irouterhandler.html
  docs/interfaces/_types_.iroutermatcher.html
  docs/interfaces/_types_.mediatype.html
  docs/interfaces/_types_.nextfunction.html
  docs/interfaces/_types_.opine.html
  docs/interfaces/_types_.request.html
  docs/interfaces/_types_.requesthandler.html
  docs/interfaces/_types_.response.html
  docs/interfaces/_types_.router.html
  docs/interfaces/_types_.routerconstructor.html
  docs/interfaces/_types_.routeroptions.html
  docs/modules/_application_.html
  docs/modules/_methods_.html
  docs/modules/_middleware_bodyparser_getcharset_.html
  docs/modules/_middleware_bodyparser_json_.html
  docs/modules/_middleware_bodyparser_raw_.html
  docs/modules/_middleware_bodyparser_read_.html
  docs/modules/_middleware_bodyparser_text_.html
  docs/modules/_middleware_bodyparser_typechecker_.html
  docs/modules/_middleware_bodyparser_urlencoded_.html
  docs/modules/_middleware_init_.html
  docs/modules/_middleware_query_.html
  docs/modules/_middleware_servestatic_.html
  docs/modules/_opine_.html
  docs/modules/_request_.html
  docs/modules/_router_index_.html
  docs/modules/_router_layer_.html
  docs/modules/_router_route_.html
  docs/modules/_types_.html
  docs/modules/_utils_compileetag_.html
  docs/modules/_utils_contentdisposition_.html
  docs/modules/_utils_definegetter_.html
  docs/modules/_utils_etag_.html
  docs/modules/_utils_finalhandler_.html
  docs/modules/_utils_fresh_.html
  docs/modules/_utils_frommap_.html
  docs/modules/_utils_merge_.html
  docs/modules/_utils_mergedescriptors_.html
  docs/modules/_utils_normalizetype_.html
  docs/modules/_utils_parseurl_.html
  docs/modules/_utils_pathtoregex_.html
  docs/modules/_utils_stringify_.html
  docs/modules/_view_.html
  lock.json
  src/application.ts
  src/router/index.ts
  src/types.ts
  test/units/app.param.test.ts
Labels: feature

#49 [#48] Support new Deno registry restrictions
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  Makefile
  deps.ts
  egg.json
  lock.json
  test/deps.ts
  version.ts
Labels: bug, chore

#55 [#50] Add app param docs
  .github/API/application.md
  .github/API/router.md
Labels: documentation

#57 [NO-ISSUE] Fixed typo in readme example
  README.md
Labels: documentation

#59 [ISSUE-58] Windows serveStatic file path handling fix
  .github/API/response.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/test.yml
  src/response.ts
  test/units/res.download.test.ts
  test/units/res.sendFile.test.ts
Labels: bug

#60 [ISSUE-58] Broken redirect directory listener
  src/middleware/serveStatic.ts
  test/fixtures/.hidden
  test/fixtures/dinos/names.txt
  test/fixtures/empty.txt
  test/fixtures/foo bar
  test/fixtures/nums.txt
  test/fixtures/todo.html
  test/fixtures/todo.txt
  test/fixtures/users/deno.txt
  test/fixtures/users/index.html
  test/units/app.param.test.ts
  test/units/serveStatic.test.ts
Labels: bug
