Repository cmorten/opine, pull requests merged in 2020-09, with the labels that each got.

#63 [#62] Remove scripts to run examples remotely where invalid
  docs/assets/js/main.js
  examples/dejs/README.md
  examples/dejs/index.ts
  examples/downloads/README.md
  examples/downloads/index.ts
  examples/error-pages/README.md
  examples/error-pages/index.ts
  examples/static-files/README.md
  examples/static-files/index.ts
  lock.json
Labels: documentation

#65 Add an example of using the Eta template engine
  examples/eta/README.md
  examples/eta/index.ts
  examples/eta/public/stylesheets/style.css
  examples/eta/views/footer.html
  examples/eta/views/header.html
  examples/eta/views/index.html
  examples/eta/views/users.html
Labels: examples

#67 (fix) deno 1.4.0 : export type
  deps.ts
  lock.json
  src/application.ts
  src/middleware/bodyParser/getCharset.ts
  src/middleware/bodyParser/json.ts
  src/middleware/bodyParser/raw.ts
  src/middleware/bodyParser/read.ts
  src/middleware/bodyParser/text.ts
  src/middleware/bodyParser/typeChecker.ts
  src/middleware/bodyParser/urlencoded.ts
  src/middleware/init.ts
  src/middleware/query.ts
  src/middleware/serveStatic.ts
  src/opine.ts
  src/request.ts
  src/response.ts
  src/router/index.ts
  src/router/layer.ts
  src/router/route.ts
  src/types.ts
  src/utils/finalHandler.ts
  src/utils/parseUrl.ts
Labels: bug

#70 [#69] Upgrade Opine to support Deno 1.4.0 and std 0.69.0
  .github/API/application.md
  .github/API/request.md
  .github/API/router.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  deps.ts
  docs/assets/js/main.js
  examples/content-negotiation/index.ts
  examples/content-negotiation/users.ts
  examples/error-pages/index.ts
  examples/error/index.ts
  examples/eta/index.ts
  lock.json
  src/request.ts
  src/response.ts
  src/types.ts
  test/deps.ts
  test/units/Route.test.ts
  test/units/Router.test.ts
  test/units/app.options.test.ts
  test/units/app.param.test.ts
  test/units/app.router.test.ts
  test/units/app.routes.error.test.ts
  test/units/app.use.test.ts
  test/units/res.format.test.ts
  test/units/res.redirect.test.ts
  test/units/res.send.test.ts
  test/units/res.sendFile.test.ts
  version.ts
Labels: dependencies

#76 Add layouts to Eta example
  examples/eta/index.ts
  examples/eta/views/index.html
  examples/eta/views/layout.html
Labels: examples

#78 [#73] Implement req.range() API
  .github/API/request.md
  deps.ts
  docs/assets/js/main.js
  lock.json
  src/request.ts
  src/types.ts
  test/units/req.range.test.ts
Labels: feature

#79 [#71] Query parser setting support
  deps.ts
  lock.json
  src/application.ts
  src/middleware/query.ts
  src/utils/compileQueryParser.ts
  src/utils/fromMap.ts
  test/units/req.query.test.ts
Labels: feature
