Repository cmorten/opine, pull requests merged in 2021-04, with the labels that each got.

#111 [#110] Support Deno 1.9.0
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  docs/index.html
  egg.json
  examples/react/server.tsx
  lock.json
  src/middleware/init.ts
  test/deps.ts
  version.ts
Labels: bug, dependencies

#112 [NO-ISSUE] Downgrade eggs publish to Deno `1.8.3` due to bug in Eggs CLI
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/publish-egg.yml
  README.md
  docs/index.html
  egg.json
  examples/react/server.tsx
  version.ts
Labels: automation

#113 [NO-ISSUE] Format lockfile to prevent Eggs CLI failure
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  Makefile
  README.md
  docs/index.html
  egg.json
  examples/react/server.tsx
  lock.json
  version.ts
Labels: chore

#118 [NO-ISSUE] Support Deno 1.9.2
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/test.yml
  .vscode/settings.json
  README.md
  deps.ts
  docs/index.html
  egg.json
  examples/eta/index.ts
  examples/react/server.tsx
  lock.json
  src/methods.ts
  src/middleware/init.ts
  test/deps.ts
  test/units/middleware.basic.test.ts
  test/units/res.append.test.ts
  test/units/res.set.test.ts
  version.ts
Labels: dependencies
