Repository cmorten/opine, pull requests merged in 2021-08, with the labels that each got.

#135 [#102] Handle broken pipe errors gracefully in opine
  src/application.ts
  src/response.ts
  src/utils/requestProxy.ts
Labels: bug

#136 docs: fix broken middleware links in request docs
  .github/API/request.md
Labels: documentation

#138 [#137] Move to skypack for npm deps
  Makefile
  deps.ts
  egg.json
  examples/dejs/index.ts
  examples/error-pages/index.ts
  examples/eta/index.ts
  examples/graphql/index.ts
  examples/mvc/deps.ts
  examples/proxy/index.test.ts
  examples/proxy/index.ts
  examples/react/server.tsx
  lock.json
Labels: bug

#140 [#139] Support Deno 1.13.1 and std 0.105.0
  .github/API/application.md
  .github/API/middlewares.md
  .github/API/opine.md
  .github/API/request.md
  .github/API/router.md
  .github/CHANGELOG.md
  .github/workflows/benchmark.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  docs/index.html
  egg.json
  examples/react/components/App.tsx
  examples/react/components/List.tsx
  examples/react/components/Title.tsx
  test/deps.ts
  version.ts
Labels: dependencies
